[tool.poetry]
name = "spine-core-aws-common"
version = "1.17.0"
description = "Python utilities for AWS Lambda functions including but not limited to tracing, logging and custom metric"
authors = ["NHSD Spine"]
include = ["spine_aws_lambda/py.typed"]
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
]
repository="https://github.com/awslabs/aws-lambda-powertools-python"
readme = "README.md"
keywords = ["nhds_spine", "spine", "nhsd", "aws", "tracing", "logging", "lambda"]
license = "MIT-0"

[tool.poetry.dependencies]
python = "^3.6.1"
aws-xray-sdk = "^2.8.0"
fastjsonschema = "^2.14.5"
boto3 = "^1.12"
jmespath = "^0.10.0"
pydantic = {version = "^1.8.2", optional = true }
email-validator = {version = "*", optional = true }

[tool.poetry.dev-dependencies]
coverage = {extras = ["toml"], version = "^5.5"}
pytest = "^6.2.2"
black = "^20.8b1"
flake8 = "^3.9.0"
flake8-black = "^0.2.1"
flake8-builtins = "^1.5.3"
flake8-comprehensions = "^3.4.0"
flake8-debugger = "^4.0.0"
flake8-fixme = "^1.1.1"
flake8-isort = "^4.0.0"
flake8-variables-names = "^0.0.4"
isort = "^5.8.0"
pytest-cov = "^2.12.1"
pytest-mock = "^3.5.1"
pdoc3 = "^0.9.2"
pytest-asyncio = "^0.15.1"
bandit = "^1.7.0"
radon = "^4.5.0"
xenon = "^0.7.3"
flake8-eradicate = "^1.0.0"
flake8-bugbear = "^21.3.2"
mkdocs-material = "^7.1.7"
mkdocs-git-revision-date-plugin = "^0.3.1"
mike = "^0.6.0"


[tool.poetry.extras]
pydantic = ["pydantic", "email-validator"]

[tool.coverage.run]
source = ["aws_lambda_powertools"]
omit = ["tests/*"]
branch = true

[tool.coverage.html]
directory = "test_report"
title = "Lambda Powertools Test Coverage"

[tool.coverage.report]
fail_under = 90
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",

    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self.debug",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",
]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120
skip = "example"

[tool.black]
line-length = 120
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | example
)
'''

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -vv"
testpaths = "./tests"
markers = "perf: marks perf tests to be deselected (deselect with '-m \"not perf\"')"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

# NOTE
# As of now, Feb 2020, flake8 don't support pyproject
# For latest: https://github.com/flying-sheep/awesome-python-packaging